steps:
- id: build-image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/webapp:1.0.0', '-f', 'webapp/Dockerfile', '.']
- id: push-image
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/webapp:1.0.0']
- id: deploy
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'webapp'
  - '--image'
  - 'gcr.io/$PROJECT_ID/webapp:1.0.0'
  - '--set-env-vars'
  - >-
    ^;^
    REDIS_HOST=$_REDIS_HOST;
  - '--allow-unauthenticated'
  - '--vpc-connector'
  - '$_REDIS_CONNECTOR'
  - '--project'
  - '$_PROJECT'
  - '--region'
  - '$_REGION'
